---
name: allow_group_deploy_token
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/23460
rollout_issue_url: 
group: group::progressive delivery
type: development
default_enabled: true
