---
name: artifacts_management_page
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/16654
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/254938
group: group::continuous integration
type: development
default_enabled: false
