---
name: auto_create_cluster_management_project
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/23946
rollout_issue_url: 
group: group::configure
type: development
default_enabled: false
