---
name: ci_dynamic_child_pipeline
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/23790
rollout_issue_url:
group: group::continuous integration
type: development
default_enabled: true
