---
name: ci_enable_live_trace
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/5255
rollout_issue_url:
group: group::continuous integration
type: development
default_enabled: false
