---
name: ci_lint_creates_pipeline_with_dry_run
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/37828
rollout_issue_url:
group: group::continuous integration
type: development
default_enabled: true
