---
name: ci_pipeline_latest
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/34160
rollout_issue_url:
group: group::continuous integration
type: development
default_enabled: true
