---
name: ci_skip_persistent_ref_existence_check
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/32391
rollout_issue_url: 
group: group::continuous integration
type: development
default_enabled: false
