---
name: cluster_agent_list
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/issues/228845
rollout_issue_url: https://gitlab.com/groups/gitlab-org/-/epics/3834
group: group::configure
type: development
default_enabled: true
