---
name: feature_flags_legacy_read_only
introduced_by_url: 
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/240985
group: group::progressive delivery
type: development
default_enabled: true
