---
name: feature_flags_new_version
introduced_by_url: 
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/258831
group: group::progressive delivery
type: development
default_enabled: true
