---
name: git_push_create_all_pipelines
introduced_by_url: https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/27205
rollout_issue_url:
group: group::continuous integration
type: development
default_enabled: false
