---
name: merge_orchestration_service
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/28532
rollout_issue_url: 
group: group::continuous integration
type: development
default_enabled: true
