---
name: merge_request_widget_graphql
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/38311
rollout_issue_url:
group: group::source code
type: development
default_enabled: false
