---
name: not_issuable_queries
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/27639
rollout_issue_url:
group: group::project management
type: development
default_enabled: true
