---
name: release_mr_issue_urls
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/18727
rollout_issue_url:
group: group::release management
type: development
default_enabled: false
