---
name: repack_after_shard_migration
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/21502
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/195597
group: group::source code
type: development
default_enabled: false
