---
name: schema_linting
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/35838
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/255919
group: group::editor
type: development
default_enabled: false
