---
name: soft_email_confirmation
introduced_by_url: https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/31245
rollout_issue_url:
group: group::acquisition
type: development
default_enabled: false
