---
name: view_diffs_file_by_file
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/35223
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/229848
group: group::source code
type: development
default_enabled: true
