---
name: vue_issuable_sidebar
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/18199
rollout_issue_url:
group: group::project management
type: development
default_enabled: false
