---
name: widget_visibility_polling
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/29318
rollout_issue_url:
group: group::source code
type: development
default_enabled: true
