include:
  - template: SAST.gitlab-ci.yml

variables:
  SECURE_ANALYZERS_PREFIX: "registry.gitlab.com/gitlab-org/security-products/analyzers2"
  SAST_EXCLUDED_PATHS: "spec, executables"
  SAST_DEFAULT_ANALYZERS: "bandit, gosec"

stages:
  - our_custom_security_stage
sast:
  stage:  our_custom_security_stage
  variables:
    SEARCH_MAX_DEPTH: 8
    SAST_BRAKEMAN_LEVEL: 2
